export const airportData = [
  { city: "서울", airport: "ICN", fullName: "인천국제공항" },
  { city: "부산", airport: "PUS", fullName: "김해국제공항" },
  { city: "뉴욕", airport: "JFK", fullName: "존 F. 케네디 국제공항" },
  { city: "도쿄", airport: "NRT", fullName: "나리타 국제공항" },
  { city: "홍콩", airport: "HKG", fullName: "홍콩 국제공항" },
  { city: "파리", airport: "CDG", fullName: "샤를 드골 국제공항" },
  { city: "런던", airport: "LHR", fullName: "히드로 공항" },
  { city: "로스앤젤레스", airport: "LAX", fullName: "로스앤젤레스 국제공항" },
  { city: "싱가포르", airport: "SIN", fullName: "창이 국제공항" },
  { city: "샌프란시스코", airport: "SFO", fullName: "샌프란시스코 국제공항" },
  { city: "시드니", airport: "SYD", fullName: "시드니 국제공항" },
  { city: "베이징", airport: "PEK", fullName: "베이징 수도 국제공항" },
  { city: "상하이", airport: "PVG", fullName: "상하이 푸둥 국제공항" },
  { city: "방콕", airport: "BKK", fullName: "수완나품 국제공항" },
  { city: "두바이", airport: "DXB", fullName: "두바이 국제공항" },
  { city: "프랑크푸르트", airport: "FRA", fullName: "프랑크푸르트 국제공항" },
  { city: "이스탄불", airport: "IST", fullName: "이스탄불 공항" },
  { city: "카타르", airport: "DOH", fullName: "하마드 국제공항" }
];
